### ISSUE TITLE
snakemake issue with the latest environment update

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline-3#100]
@jbloom I'm getting the following `Snakemake` error for the latest pipeline when I run `snakemake -j 16 --rerun-incomplete --software-deployment-method conda -s dms-vep-pipeline-3/Snakefile`. I tired doing this from `dms-vep-pipeline-3`environments both on BloomLab and my own conda and I get the same error. 

```
Traceback (most recent call last):
  File "/home/bdadonai/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/snakemake/cli.py", line 1893, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/home/bdadonai/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/snakemake/api.py", line 326, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/bdadonai/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/snakemake/api.py", line 436, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bdadonai/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/snakemake/api.py", line 383, in _workflow
    workflow.include(
  File "/home/bdadonai/miniconda3/envs/dms-vep-pipeline-3/lib/python3.11/site-packages/snakemake/workflow.py", line 1379, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/fh/fast/bloom_j/computational_notebooks/bdadonai/2024/SARS-CoV-2_Omicron_BA.2_spike_DMS_COV3560/dms-vep-pipeline-3/Snakefile", line 32, in <module>
AssertionError
```

**Comment by jbloom** [comment]
It's actually due to an error in your `barcode_runs` CSV file, but the error message is not very helpful!

I am making a pull request right now in #101 to provide a better error message; when that is merged it should make it obvious how to fix this when you see the error message from updated pipeline (if it doesn't, then let me know).

**Comment by jbloom** [comment]
Run with the latest version of `dms-vep-pipeline-3` and hopefully you will get a diagnosable error.
