### ISSUE TITLE
Pipeline not running without antibody escape

### ISSUE THREAD

**Issue by arjunaditham** [dms-vep/dms-vep-pipeline-3#102]
Tried running pipeline setting antibody escape in config to empty dictionaries; summary document is not working. (Repo is up-to-date with my input yml files). 

Error log for the summary file is below:

Traceback (most recent call last):
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/bin/papermill", line 11, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 47
     45 for prop in other_props:
     46     if not re.fullmatch("[\w ]+", prop):
---> 47         raise ValueError("non-alphanumeric name for property: {prop}")
     48     other_props[prop] = (
     49         pd.concat(
     50             [
   (...)
     61         .query("(mutant in @alphabet) and (wildtype in @alphabet)")
     62     )
     63     assert other_props[prop]["site_mutant"].nunique() == len(other_props[prop])

ValueError: non-alphanumeric name for property: {prop}

**Comment by jbloom** [comment]
@arjunaditham @caelanradford, for now you should be able to fix this problem by setting `antibody_escape_config: null` in `config.yaml`.

It really should work with empty dict too and I will eventually fix to work with that, but for now I **think** above will solve problem. Let me know if it does not.

**Comment by arjunaditham** [comment]
I tried `antibody_escape_config: null` in config.yaml and got this error during the snakemake dry run:

Building DAG of jobs...
InputFunctionException in rule format_altair_html in file /fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/dms-vep-pipeline-3/common.smk, line 7:
Error:
  NameError: name 'assays' is not defined
Wildcards:
  chart=summaries/summary_overlaid
Traceback:
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/dms-vep-pipeline-3/common_funcs.smk", line 33, in format_altair_html_chart_params (rule format_altair_html, line 9, /fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/dms-vep-pipeline-3/common.smk)

**Comment by jbloom** [comment]
@arjunaditham this is fixed in version 3.6.2

Note it now just works with `antibody_escape_config: null`, not the empty dict. I think that is fine because that is what the docs say will work.

**Comment by arjunaditham** [comment]
I pulled 3.6.2 and tried running with `antibody_escape_config: null` but I got this same error.

Traceback (most recent call last):
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/bin/papermill", line 11, in <module>
    sys.exit(papermill())
             ^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/execute.py", line 128, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/fh/fast/bloom_j/computational_notebooks/aaditham/2024/RABV_Pasteur_G_DMS/.snakemake/conda/f1180436d2da8354655661ed54d7d6e1_/lib/python3.11/site-packages/papermill/execute.py", line 232, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [8]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 47
     45 for prop in other_props:
     46     if not re.fullmatch("[\w ]+", prop):
---> 47         raise ValueError("non-alphanumeric name for property: {prop}")
     48     other_props[prop] = (
     49         pd.concat(
     50             [
   (...)
     61         .query("(mutant in @alphabet) and (wildtype in @alphabet)")
     62     )
     63     assert other_props[prop]["site_mutant"].nunique() == len(other_props[prop])

ValueError: non-alphanumeric name for property: {prop}

**Comment by jbloom** [comment]
Can you push the latest version of your repo that is giving this error and let me know that exact version when pushed, and I will take a look.

**Comment by arjunaditham** [comment]
just pushed

**Comment by arjunaditham** [comment]
This should be the version: 0815b96

If I gave the wrong information please let me know.

**Comment by jbloom** [comment]
@arjunaditham, set `summaries_config: null` in the configuration and it will work.

The summaries is really only intended when you have data from multiple assays to show together.
