### ISSUE TITLE
barcode counting failing

### ISSUE THREAD

**Issue by caelanradford** [dms-vep/dms-vep-pipeline-3#175]
I am getting an error every time I try to run the pipeline, during barcode counting.

I updated to the latest version of the pipeline today, and was re-running my analysis when the issue started. 

Not sure what is causing this issue. I am running it in an sbatch submission to gizmo. 

```
Traceback (most recent call last):
  File "/fh/fast/bloom_j/computational_notebooks/ceradfor/2024/HIV_Envelope_BF520_DMS/.snakemake/scripts/tmp10_0iz4i.count_barcodes.py", line 23, in <module>
    library = snakemake.params.library
              ^^^^^^^^^^^^^^^^
  File "/fh/fast/bloom_j/computational_notebooks/ceradfor/2024/HIV_Envelope_BF520_DMS/.snakemake/conda/37c005d6af88cb84d9a1497237773b19_/lib/python3.12/site-packages/snakemake/script/__init__.py", line 117, in params
    params = io_.Params(toclone=list(self._params_store))
                                     ^^^^^^^^^^^^^^^^^^
AttributeError: 'Snakemake' object has no attribute '_params_store'
```

**Comment by jbloom** [comment]
And you are sure you are running from a `conda` environment built on the current version of `environment.yml` and are using `--software-deployment-method conda`?

If so, push a branch of the repo that gives this error, and post here exactly what that is and I will try to troubleshoot.

**Comment by caelanradford** [comment]
It was indeed an issue with the environment I was running it in. Rebuilding the environment seems to have fixed the issue.
